import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "./components/LayoutWrapper";
import { NavBar } from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ height: "100%", width: "100%", display: "flex" }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          height: "100%",
          width: "100%",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <LayoutWrapper>
          <NavBar />
          <div
            style={{
              padding: 10,
              height: "100%",
              display: "flex",
              flexDirection: "column",
              width: "100%",
            }}
          >
            {children}
          </div>
        </LayoutWrapper>
      </body>
    </html>
  );
}
