import type { Metadata } from "next";
import "./globals.css";
import "./styles/global.css";
import LayoutWrapper from "./components/LayoutWrapper";
import { NavBar } from "./components/NavBar/NavBar";
import { MediaConfig } from "./components/MediaConfig";
import DirectMessageList from "./components/DirectMessageList";
import MainPage from "./components/MainPage/MainPage";
import AppHeader from "./components/AppHeader/AppHeader";
import ServersSidebar from "./components/ServersSidebar";

// const ggSans = localFont({
//   src: "./styles/fonts/ggsansRegular.woff",
//   display: "swap",
//   variable: "--font-ggsans",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ height: "100%", width: "100%" }}>
      <body
        className={``}
        style={{
          height: "100%",
          width: "100%",
          flex: 1,
          display: "flex",
          flexDirection: "column",
          maxHeight: "100%",
          backgroundColor: "oklab(0.183076 0.00112209 -0.00388214)",
        }}
      >
        <LayoutWrapper>
          <NavBar />
          <AppHeader />
          <div style={{ flex: 1, overflow: "hidden", display: "flex" }}>
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                justifyContent: "space-between",
              }}
            >
              <div
                style={{
                  display: "flex",
                  flex: 1,
                  overflow: "auto",
                  width: 400,
                }}
              >
                <ServersSidebar />
                <DirectMessageList />
              </div>
              <MediaConfig />
            </div>
            <div
              style={{ height: "100%", width: "100%", overflow: "hidden auto" }}
            >
              {children}
            </div>
          </div>
          {/* <MainPage /> */}
          {/* <div
            style={{
              padding: 10,
              height: "100%",
              display: "flex",
              flexDirection: "column",
              width: "100%",
            }}
          >
            {children}
          </div> */}
        </LayoutWrapper>
      </body>
    </html>
  );
}
