import { EditMessageData, Io, MessageData, SocketServer } from "@socket/types";
import { Request, Response } from "express";
import {
  createMessage,
  findMessages,
  updateMessage,
} from "@services/messageService";
import { emitOnlyToUser } from "@utils/handleSocketEmit";

export const sendMessage = async (
  io: Io,
  socket: SocketServer,
  messageData: MessageData,
  statusCallback: (...args: any) => void // Used to acknowledge the operation with the client
) => {
  const { content, channelId, tempId, authorId } = messageData;

  try {
    // Optimistic UI
    // We emit the received message instantly with a temporary ID,
    // that way we don't have to wait for prisma.message.create to finish its operation.
    // We then update the clients' local state with the ID generated by the DB.
    // We include the temporary ID in the broadcast so that all clients will be able to reference it in their local states.
    if (!content || !channelId || !authorId) {
      throw new Error("Invalid data, missing fields.");
    }
    const savedMessage = await createMessage(messageData);
    console.log(`channel-${channelId}`)
    socket.to(`channel-${channelId}`).emit("receive-message", savedMessage);

    socket
      .to(`room-${savedMessage.channel.roomId}-notifications`)
      .except(`channel-${channelId}`)
      .emit(`new-background-message`, savedMessage);

    statusCallback({
      tempId,
      ...savedMessage,
      status: "Success",
    });

    // socket.emit("send-message-status", {
    //   tempId,
    //   ...savedMessage,
    //   status: "Success",
    // });
  } catch (error) {
    statusCallback({
      error: `Failed to send message: ${error}`,
      tempId,
      channelId,
      status: "Error",
    });
  }
};

export const editMessage = async (
  io: Io,
  socket: SocketServer,
  messageData: EditMessageData,
  statusCallback: (...args: any) => void
) => {
  const { content, channelId, id, prevContent } = messageData;

  try {
    if (!content || !channelId || !id) {
      throw new Error("Invalid data, missing content.");
    }

    const updatedMessage = await updateMessage(messageData);
    // socket.emit("edit-message-status", {
    //   ...updatedMessage,
    //   status: "Success",
    // });
    statusCallback({
      ...updatedMessage,
      status: "Success",
    });
    socket.to(`channel-${channelId}`).emit("edit-message-incoming", {
      ...updatedMessage,
      status: "Success",
    });
  } catch (error) {
    // If the creation operation fails, we notify the clients to update their UI.
    // socket.emit("edit-message-status", {
    //   error: `Failed to send message: ${error}`,
    //   id,
    //   content: prevContent,
    //   status: "Error",
    // });
    statusCallback({
      error: `Failed to send message: ${error}`,
      id,
      content: prevContent,
      status: "Error",
    });
  }
};

export const getMessages = async (req: Request, res: Response) => {
  const { roomId } = req.params;

  try {
    const messages = await findMessages(roomId);

    res.status(200).json(messages);
  } catch (error) {
    console.error("Error fetching messages:", error);
    res.status(500).json({ error: "Failed to fetch messages." });
  }
};
